### Health check for middleware, no authentication required
GET {{HostAddress}}/healthcheck
Accept: application/json

### Initialize the API, especially the CosmosDB container
POST {{HostAddress}}/:initialize
Authorization: Bearer {{AdminRoleToken}}
Accept: application/json

### Create a new tenant if it doesn't exist...
POST {{HostAddress}}/tenants
Content-Type: application/json
Authorization: Bearer {{AdminRoleToken}}
Accept: application/json

{
  "uuid": "4BE4E0B8-AABE-4C48-A5E9-47F07106FC9E",
  "slug": "tenant-1",
  "title": "Tenant 1",
  "plan": "Premium"
}

### Get list of components for a tenant
GET {{HostAddress}}/baypogyiq/components
Accept: application/json
Authorization: Bearer {{AdminRoleToken}}

### Create a new component for a tenant, requires Agent as that is the
### only process that should be running this.
POST {{HostAddress}}/tenant-1/components
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{AgentRoleToken}}

{
  "uuid": "CADB12F7-07F0-4BE6-B92C-9FB0A4217CC1",
  "slug": "component-2",
  "code": "INV-2",
  "title": "Invoice #12345",
  "description": "A sample invoice",
  "keywords": "sample invoice 12345 and stuff",
  "fullText": "All the words",
  "discriminator": "Component"
}

