version: '3.4'

services:
  sample.components.api:
    image: ${DOCKER_REGISTRY-}samplecomponentsapi
    build:
      context: .
      dockerfile: Sample.Components.Api/Dockerfile

  # RabbitMQ docker image for local development only.
  # Using image from MassTransit, see https://masstransit.io/quick-starts/rabbitmq
  # Login in http://localhost:15672, with guest/guest.
  sample.servicebus.stub:
    image: masstransit/rabbitmq
    ports:
    - 15672:15672
    - 5672:5672

  sample.components.agent:
    image: ${DOCKER_REGISTRY-}samplecomponentsagent
    build:
      context: .
      dockerfile: Sample.Components.Agent/Dockerfile

